INFO 2024-05-21 02:27:28,796 autoreload 12488 8572Watching for file changes with StatReloader
INFO 2024-05-21 02:27:30,895 views 12488 8360Index page accessed
INFO 2024-05-21 02:27:30,932 basehttp 12488 8360"GET / HTTP/1.1" 200 3223
WARNING 2024-05-21 02:27:31,045 log 12488 8360Not Found: /favicon.ico
WARNING 2024-05-21 02:27:31,046 basehttp 12488 8360"GET /favicon.ico HTTP/1.1" 404 2636
ERROR 2024-05-21 02:27:42,024 log 12488 8360Internal Server Error: /list_orders/6/
Traceback (most recent call last):
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\_GB_django\my_dz\myapp\views.py", line 34, in list_orders
    orders_last_week = [x for x in orders if x.date_ordered > datetime.date.today - datetime.timedelta(days=7)]
                                                              ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'builtin_function_or_method' and 'datetime.timedelta'
ERROR 2024-05-21 02:27:42,027 basehttp 12488 8360"GET /list_orders/6/ HTTP/1.1" 500 65452
INFO 2024-05-21 02:28:02,541 autoreload 12488 8572C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 02:28:03,322 autoreload 10108 9668Watching for file changes with StatReloader
INFO 2024-05-21 02:28:04,922 basehttp 10108 12100"GET /list_orders/6/ HTTP/1.1" 200 320
INFO 2024-05-21 02:29:01,182 autoreload 10108 9668C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 02:29:01,899 autoreload 5464 7728Watching for file changes with StatReloader
INFO 2024-05-21 02:29:04,041 basehttp 5464 9092"GET /list_orders/6/ HTTP/1.1" 200 562
INFO 2024-05-21 02:31:09,958 autoreload 5464 7728C:\_GB_django\my_dz\myapp\models.py changed, reloading.
INFO 2024-05-21 02:31:10,696 autoreload 14012 11124Watching for file changes with StatReloader
INFO 2024-05-21 02:31:12,489 basehttp 14012 14072"GET /list_orders/6/ HTTP/1.1" 200 492
INFO 2024-05-21 02:33:23,975 autoreload 14012 11124C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 02:33:24,617 autoreload 10564 12780Watching for file changes with StatReloader
INFO 2024-05-21 02:38:11,950 autoreload 10564 12780C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 02:38:12,598 autoreload 5512 3716Watching for file changes with StatReloader
INFO 2024-05-21 02:40:34,740 autoreload 5512 3716C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 02:40:35,407 autoreload 7216 6240Watching for file changes with StatReloader
INFO 2024-05-21 02:41:36,969 autoreload 7216 6240C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 02:41:37,653 autoreload 13336 8384Watching for file changes with StatReloader
INFO 2024-05-21 02:42:26,527 autoreload 13336 8384C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 02:42:27,207 autoreload 872 5792Watching for file changes with StatReloader
INFO 2024-05-21 02:42:29,004 basehttp 872 10872"GET /list_orders/6/ HTTP/1.1" 200 639
INFO 2024-05-21 02:45:55,166 autoreload 872 5792C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 02:45:55,815 autoreload 13744 2168Watching for file changes with StatReloader
INFO 2024-05-21 02:46:33,194 autoreload 13744 2168C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 02:46:33,950 autoreload 14192 8268Watching for file changes with StatReloader
INFO 2024-05-21 02:48:45,899 autoreload 14192 8268C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 02:48:46,588 autoreload 5360 11492Watching for file changes with StatReloader
ERROR 2024-05-21 02:50:17,073 log 5360 2496Internal Server Error: /list_orders/6/
Traceback (most recent call last):
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\_GB_django\my_dz\myapp\views.py", line 39, in list_orders
    for x in orders_last_week:
TypeError: 'NoneType' object is not iterable
ERROR 2024-05-21 02:50:17,077 basehttp 5360 2496"GET /list_orders/6/ HTTP/1.1" 500 65631
INFO 2024-05-21 02:51:51,433 autoreload 5360 11492C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 02:51:52,154 autoreload 3200 5464Watching for file changes with StatReloader
INFO 2024-05-21 02:52:01,291 autoreload 3200 5464C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 02:52:02,023 autoreload 6744 11976Watching for file changes with StatReloader
INFO 2024-05-21 02:52:09,979 autoreload 6744 11976C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 02:52:10,625 autoreload 10008 6900Watching for file changes with StatReloader
ERROR 2024-05-21 02:52:13,574 log 10008 12088Internal Server Error: /list_orders/6/
Traceback (most recent call last):
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\_GB_django\my_dz\myapp\views.py", line 38, in list_orders
    if len(orders_last_week)>0:
       ^^^^^^^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
ERROR 2024-05-21 02:52:13,577 basehttp 10008 12088"GET /list_orders/6/ HTTP/1.1" 500 65520
INFO 2024-05-21 02:54:21,884 autoreload 10008 6900C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 02:54:22,584 autoreload 7252 5372Watching for file changes with StatReloader
ERROR 2024-05-21 02:54:26,895 log 7252 14012Internal Server Error: /list_orders/6/
Traceback (most recent call last):
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\_GB_django\my_dz\myapp\views.py", line 39, in list_orders
    if len(orders_last_week)>0:
       ^^^^^^^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
ERROR 2024-05-21 02:54:26,897 basehttp 7252 14012"GET /list_orders/6/ HTTP/1.1" 500 65556
INFO 2024-05-21 02:54:49,785 autoreload 7252 5372C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 02:54:50,511 autoreload 11760 11984Watching for file changes with StatReloader
INFO 2024-05-21 02:54:52,166 autoreload 11760 11984C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 02:54:52,836 autoreload 1352 10496Watching for file changes with StatReloader
ERROR 2024-05-21 02:54:54,697 log 1352 4084Internal Server Error: /list_orders/6/
Traceback (most recent call last):
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\_GB_django\my_dz\myapp\views.py", line 39, in list_orders
    if len(orders_last_week)>0:
       ^^^^^^^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
ERROR 2024-05-21 02:54:54,700 basehttp 1352 4084"GET /list_orders/6/ HTTP/1.1" 500 65556
INFO 2024-05-21 02:56:05,229 autoreload 1352 10496C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 02:56:05,937 autoreload 6564 11148Watching for file changes with StatReloader
ERROR 2024-05-21 02:56:07,135 log 6564 7280Internal Server Error: /list_orders/6/
Traceback (most recent call last):
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\_GB_django\my_dz\myapp\views.py", line 39, in list_orders
    if len(orders_last_week)>0:
       ^^^^^^^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
ERROR 2024-05-21 02:56:07,138 basehttp 6564 7280"GET /list_orders/6/ HTTP/1.1" 500 65544
INFO 2024-05-21 02:57:13,000 autoreload 6564 11148C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 02:57:13,648 autoreload 10748 13252Watching for file changes with StatReloader
INFO 2024-05-21 02:57:29,993 autoreload 10748 13252C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 02:57:30,730 autoreload 9784 4596Watching for file changes with StatReloader
ERROR 2024-05-21 02:57:32,315 log 9784 3820Internal Server Error: /list_orders/6/
Traceback (most recent call last):
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\_GB_django\my_dz\myapp\views.py", line 39, in list_orders
    if len(orders_last_week)>0:
       ^^^^^^^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
ERROR 2024-05-21 02:57:32,318 basehttp 9784 3820"GET /list_orders/6/ HTTP/1.1" 500 65545
INFO 2024-05-21 02:57:50,645 autoreload 9784 4596C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 02:57:51,380 autoreload 2384 12332Watching for file changes with StatReloader
ERROR 2024-05-21 02:57:52,380 log 2384 5192Internal Server Error: /list_orders/6/
Traceback (most recent call last):
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\_GB_django\my_dz\myapp\views.py", line 50, in list_orders
    if len(orders_last_month)>0:
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
ERROR 2024-05-21 02:57:52,383 basehttp 2384 5192"GET /list_orders/6/ HTTP/1.1" 500 65916
INFO 2024-05-21 02:59:37,119 autoreload 2384 12332C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 02:59:37,791 autoreload 7616 10872Watching for file changes with StatReloader
ERROR 2024-05-21 02:59:40,095 log 7616 7920Internal Server Error: /list_orders/6/
Traceback (most recent call last):
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\_GB_django\my_dz\myapp\views.py", line 51, in list_orders
    if len(orders_last_month)>0:
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
ERROR 2024-05-21 02:59:40,098 basehttp 7616 7920"GET /list_orders/6/ HTTP/1.1" 500 66101
INFO 2024-05-21 03:02:23,744 autoreload 7616 10872C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 03:02:24,431 autoreload 9460 3228Watching for file changes with StatReloader
INFO 2024-05-21 03:03:23,823 autoreload 9460 3228C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 03:03:24,465 autoreload 9404 6224Watching for file changes with StatReloader
INFO 2024-05-21 03:03:33,507 autoreload 9404 6224C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 03:03:34,168 autoreload 1912 9128Watching for file changes with StatReloader
ERROR 2024-05-21 03:03:36,952 log 1912 13048Internal Server Error: /list_orders/6/
Traceback (most recent call last):
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\_GB_django\my_dz\myapp\views.py", line 74, in list_orders
    return render (request, 'myapp/list_orders.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\defaulttags.py", line 860, in do_for
    sequence = parser.compile_filter(bits[in_index + 1])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 597, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 698, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '{data_week}' from '{data_week}'
ERROR 2024-05-21 03:03:36,967 basehttp 1912 13048"GET /list_orders/6/ HTTP/1.1" 500 173912
ERROR 2024-05-21 03:04:38,654 log 1912 13048Internal Server Error: /list_orders/6/
Traceback (most recent call last):
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 502, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'end'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\_GB_django\my_dz\myapp\views.py", line 74, in list_orders
    return render (request, 'myapp/list_orders.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\defaulttags.py", line 861, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 504, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 555, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 9: 'end', expected 'empty' or 'endfor'. Did you forget to register or load this tag?
ERROR 2024-05-21 03:04:38,666 basehttp 1912 13048"GET /list_orders/6/ HTTP/1.1" 500 178578
INFO 2024-05-21 03:06:46,067 basehttp 1912 13048"GET /list_orders/6/ HTTP/1.1" 200 195
INFO 2024-05-21 03:07:33,181 autoreload 1912 9128C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 03:07:33,911 autoreload 14048 9588Watching for file changes with StatReloader
INFO 2024-05-21 03:07:35,575 autoreload 14048 9588C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 03:07:36,257 autoreload 9172 14332Watching for file changes with StatReloader
INFO 2024-05-21 03:07:37,938 autoreload 9172 14332C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 03:07:38,620 autoreload 8892 9224Watching for file changes with StatReloader
INFO 2024-05-21 03:07:42,295 basehttp 8892 14308"GET /list_orders/6/ HTTP/1.1" 200 195
INFO 2024-05-21 03:08:19,376 autoreload 8892 9224C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 03:08:20,094 autoreload 6396 10340Watching for file changes with StatReloader
INFO 2024-05-21 03:08:21,715 basehttp 6396 10536"GET /list_orders/6/ HTTP/1.1" 200 195
INFO 2024-05-21 03:09:37,833 autoreload 6396 10340C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 03:09:38,510 autoreload 1924 13764Watching for file changes with StatReloader
INFO 2024-05-21 03:09:43,380 autoreload 1924 13764C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 03:09:44,069 autoreload 8700 9640Watching for file changes with StatReloader
ERROR 2024-05-21 03:09:46,376 log 8700 9348Internal Server Error: /list_orders/6/
Traceback (most recent call last):
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\_GB_django\my_dz\myapp\views.py", line 39, in list_orders
    if order.date_ordered < (datetime.datetime.now() - datetime.timedelta(days=7)):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: can't compare datetime.datetime to datetime.date
ERROR 2024-05-21 03:09:46,380 basehttp 8700 9348"GET /list_orders/6/ HTTP/1.1" 500 65796
INFO 2024-05-21 03:10:14,340 autoreload 8700 9640C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 03:10:15,017 autoreload 3020 11456Watching for file changes with StatReloader
INFO 2024-05-21 03:10:17,685 autoreload 3020 11456C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 03:10:18,377 autoreload 9136 1660Watching for file changes with StatReloader
INFO 2024-05-21 03:10:20,042 autoreload 9136 1660C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 03:10:20,729 autoreload 10476 5804Watching for file changes with StatReloader
INFO 2024-05-21 03:10:22,076 basehttp 10476 12212"GET /list_orders/6/ HTTP/1.1" 200 195
INFO 2024-05-21 03:11:47,917 autoreload 10476 5804C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 03:11:48,609 autoreload 12700 6480Watching for file changes with StatReloader
INFO 2024-05-21 03:11:51,796 basehttp 12700 5192"GET /list_orders/6/ HTTP/1.1" 200 195
INFO 2024-05-21 03:12:25,403 autoreload 12700 6480C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 03:12:26,076 autoreload 11992 3528Watching for file changes with StatReloader
INFO 2024-05-21 03:12:29,829 autoreload 11992 3528C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 03:12:30,481 autoreload 11844 12676Watching for file changes with StatReloader
INFO 2024-05-21 03:12:32,556 basehttp 11844 6780"GET /list_orders/6/ HTTP/1.1" 200 1019
INFO 2024-05-21 03:12:58,586 autoreload 11844 12676C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 03:12:59,256 autoreload 10948 7752Watching for file changes with StatReloader
INFO 2024-05-21 03:13:01,751 basehttp 10948 5108"GET /list_orders/6/ HTTP/1.1" 200 1019
INFO 2024-05-21 03:13:41,187 autoreload 10948 7752C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 03:13:41,848 autoreload 9636 5068Watching for file changes with StatReloader
INFO 2024-05-21 03:13:45,613 autoreload 9636 5068C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 03:13:46,302 autoreload 5980 9292Watching for file changes with StatReloader
INFO 2024-05-21 03:13:49,193 basehttp 5980 11196"GET /list_orders/6/ HTTP/1.1" 200 680
INFO 2024-05-21 03:14:51,264 autoreload 5980 9292C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 03:14:51,993 autoreload 7760 1496Watching for file changes with StatReloader
INFO 2024-05-21 03:15:10,456 autoreload 7760 1496C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 03:15:11,126 autoreload 11112 2732Watching for file changes with StatReloader
INFO 2024-05-21 03:15:16,010 autoreload 11112 2732C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 03:15:16,696 autoreload 6140 5192Watching for file changes with StatReloader
INFO 2024-05-21 03:15:18,365 autoreload 6140 5192C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 03:15:19,072 autoreload 8600 6480Watching for file changes with StatReloader
INFO 2024-05-21 03:16:12,560 basehttp 8600 1208"GET /list_orders/6/ HTTP/1.1" 200 2261
INFO 2024-05-21 03:18:21,748 autoreload 8600 6480C:\_GB_django\my_dz\myapp\views.py changed, reloading.
INFO 2024-05-21 03:18:22,449 autoreload 13308 12868Watching for file changes with StatReloader
INFO 2024-05-21 03:18:24,276 basehttp 13308 9056"GET /list_orders/6/ HTTP/1.1" 200 2261
INFO 2024-05-21 03:18:26,437 basehttp 13308 9056"GET /list_orders/6/ HTTP/1.1" 200 2261
